import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { MongoClient } from 'mongodb';
import { randomUUID, randomInt, createHash } from 'node:crypto';

const app = express();
const frontendUrl = process.env.FRONTEND_URL || 'https://quick-cart-three-chi.vercel.app';
const allowedOrigins = new Set([frontendUrl, 'https://ad3n1x.github.io', 'https://ad3n1x.github.io/QuickCart', 'http://localhost:5173', 'http://localhost:4173']);
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');if(req.secure||req.headers['x-forwarded-proto']==='https')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next();});
app.use((req,res,next)=>{if(req.path.startsWith('/api/') && process.env.NODE_ENV==='production' && req.headers['x-forwarded-proto']!=='https')return res.status(400).json({error:'HTTPS is required.',code:'HTTPS_REQUIRED'});next();});
app.use(cors({ origin: (origin, callback) => { if (!origin || allowedOrigins.has(origin)) return callback(null, true); callback(new Error('Origin not allowed by CORS.')); } }));
app.use(express.json({ limit: '2mb' }));

const mongoUri = process.env.MONGODB_URI;
const jwtSecret = process.env.JWT_SECRET;
const brevoApiKey = process.env.BREVO_API_KEY;
const brevoFromEmail = process.env.BREVO_FROM_EMAIL;
const brevoFromName = process.env.BREVO_FROM_NAME || 'QuickCart';
const alatPaySecretKey = process.env.ALATPAY_SECRET_KEY;
const alatPayPublicKey = process.env.ALATPAY_PUBLIC_KEY;
const alatPayBusinessId = process.env.ALATPAY_BUSINESS_ID;
const alatPayBaseUrl = process.env.ALATPAY_BASE_URL || 'https://apibox.alatpay.ng/bank-transfer';
if (!mongoUri) console.warn('MONGODB_URI is not configured.');
if (!jwtSecret) console.warn('JWT_SECRET is not configured.');
if (!brevoApiKey) console.warn('BREVO_API_KEY is not configured.');
if (!brevoFromEmail) console.warn('BREVO_FROM_EMAIL is not configured.');
if (!alatPaySecretKey) console.warn('ALATPAY_SECRET_KEY is not configured.');
if (!alatPayBusinessId) console.warn('ALATPAY_BUSINESS_ID is not configured.');

let dbPromise;
async function db() { if (!mongoUri) throw new Error('MONGODB_URI is not configured.'); if (!dbPromise) { const client = new MongoClient(mongoUri); dbPromise = client.connect().then(c => c.db('quickcart')); } return dbPromise; }
function tokenFor(user) { if (!jwtSecret) throw new Error('JWT_SECRET is not configured.'); return jwt.sign({ sub: user.id, email: user.email, name: user.name }, jwtSecret, { expiresIn: '7d' }); }
function auth(req, res, next) { try { const h=String(req.headers.authorization||''); const token=h.startsWith('Bearer ')?h.slice(7).trim():''; if(!token||!jwtSecret)return res.status(401).json({error:'Authentication required.',code:'AUTH_REQUIRED'}); const payload=jwt.verify(token,jwtSecret); if(!payload?.sub)return res.status(401).json({error:'Invalid session.',code:'INVALID_SESSION'}); req.user=payload; next(); } catch { return res.status(401).json({error:'Invalid or expired session.',code:'INVALID_SESSION'}); } }
const hashToken = token => createHash('sha256').update(token).digest('hex');
const createOtp = () => String(randomInt(100000, 1000000));
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const now = () => new Date().toISOString();
const slugify = value => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);
async function getUserStore(database, req) { const stores=database.collection('stores'); const requestedId=String(req.headers['x-store-id']||''); if(requestedId){ const selected=await stores.findOne({id:requestedId,userId:req.user.sub}); if(selected)return selected; } return stores.findOne({userId:req.user.sub},{sort:{createdAt:1}}); }

async function sendVerificationEmail(email,name,otp){
 if(!brevoApiKey) throw new Error('BREVO_API_KEY is not configured.');
 if(!brevoFromEmail) throw new Error('BREVO_FROM_EMAIL is not configured.');
 const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{accept:'application/json','api-key':brevoApiKey,'content-type':'application/json'},body:JSON.stringify({sender:{name:brevoFromName,email:brevoFromEmail},to:[{email,name}],subject:'Your QuickCart verification code',textContent:`Hi ${name||'there'}, your QuickCart verification code is ${otp}. It expires in 10 minutes.`,htmlContent:`<html><body style="font-family:Arial,sans-serif;background:#f5f8f6;padding:30px"><div style="max-width:520px;margin:auto;background:#fff;padding:32px;border-radius:16px"><h1>Welcome to QuickCart 👋</h1><p>Hi ${name||'there'},</p><p>Use this code to verify your email:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px;background:#eef5f1;padding:18px;text-align:center;border-radius:12px">${otp}</div><p>This code expires in 10 minutes.</p></div></body></html>`})});
 const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.message||'Unable to send verification email.'); return data;
}

app.get('/api/_healthcheck',async(_req,res)=>{try{const database=await db();await database.command({ping:1});res.json({ok:true,database:'quickcart',emailProvider:'brevo'});}catch(error){console.error(error);res.status(503).json({ok:false,error:error.message||'Database connection failed.'});}});

app.post('/api/auth/signup',async(req,res)=>{try{const database=await db(),users=database.collection('users');const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),name=String(req.body.name||'').trim();if(!name||name.length>100||!emailPattern.test(email)||password.length<6||password.length>128)return res.status(400).json({error:'Enter a valid name and email, and a password between 6 and 128 characters.',code:'INVALID_SIGNUP'});if(await users.findOne({email}))return res.status(409).json({error:'An account with that email already exists.',code:'EMAIL_EXISTS'});const otp=createOtp();const user={id:randomUUID(),name,email,passwordHash:await bcrypt.hash(password,12),emailVerified:false,emailVerificationOtpHash:hashToken(otp),emailVerificationExpiresAt:new Date(Date.now()+600000),emailVerificationAttempts:0,emailVerificationSentAt:new Date(),emailVerificationResends:0,createdAt:now()};try{await users.insertOne(user);await sendVerificationEmail(email,name,otp);}catch(e){await users.deleteOne({id:user.id});throw e;}res.status(201).json({message:'Account created. Enter the verification code sent to your email.',requiresVerification:true,email});}catch(error){console.error(error);if(error?.code===11000)return res.status(409).json({error:'An account with that email already exists.',code:'EMAIL_EXISTS'});res.status(503).json({error:'Unable to send the verification email. Please try again.',code:'EMAIL_DELIVERY_FAILED'});}});
app.post('/api/auth/verify-otp',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),otp=String(req.body.otp||'').trim();if(!emailPattern.test(email)||!/^[0-9]{6}$/.test(otp))return res.status(400).json({error:'Enter a valid email and the 6-digit verification code.',code:'INVALID_OTP'});const database=await db(),users=database.collection('users'),user=await users.findOne({email});if(!user)return res.status(404).json({error:'Account not found.',code:'ACCOUNT_NOT_FOUND'});if(user.emailVerified)return res.json({message:'Email is already verified.',token:tokenFor(user),user:{id:user.id,name:user.name,email:user.email}});if(Number(user.emailVerificationAttempts||0)>=5)return res.status(429).json({error:'Too many incorrect attempts. Request a new code.',code:'OTP_ATTEMPTS_EXCEEDED'});if(!user.emailVerificationExpiresAt||new Date(user.emailVerificationExpiresAt)<=new Date())return res.status(400).json({error:'This code has expired. Request a new code.',code:'OTP_EXPIRED'});if(hashToken(otp)!==user.emailVerificationOtpHash){const result=await users.updateOne({id:user.id,emailVerified:false,emailVerificationAttempts:{$lt:5}},{$inc:{emailVerificationAttempts:1}});if(!result.matchedCount)return res.status(429).json({error:'Too many incorrect attempts. Request a new code.',code:'OTP_ATTEMPTS_EXCEEDED'});return res.status(400).json({error:'Incorrect verification code.',code:'INVALID_OTP'});}await users.updateOne({id:user.id,emailVerified:false},{$set:{emailVerified:true},$unset:{emailVerificationOtpHash:'',emailVerificationExpiresAt:'',emailVerificationAttempts:'',emailVerificationSentAt:'',emailVerificationResends:''}});res.json({message:'Email verified successfully.',token:tokenFor({...user,emailVerified:true}),user:{id:user.id,name:user.name,email:user.email}});}catch(error){console.error(error);res.status(500).json({error:'Unable to verify email.',code:'OTP_VERIFY_FAILED'});}});
app.post('/api/auth/resend-otp',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();if(!emailPattern.test(email))return res.status(400).json({error:'Enter a valid email address.',code:'INVALID_EMAIL'});const database=await db(),users=database.collection('users'),user=await users.findOne({email});if(!user)return res.status(404).json({error:'No account was found with that email.',code:'ACCOUNT_NOT_FOUND'});if(user.emailVerified)return res.status(400).json({error:'That email is already verified. You can sign in.',code:'ALREADY_VERIFIED'});const sentAt=user.emailVerificationSentAt?new Date(user.emailVerificationSentAt).getTime():0;const elapsed=Date.now()-sentAt;if(sentAt&&elapsed<60000)return res.status(429).json({error:`Please wait ${Math.ceil((60000-elapsed)/1000)} seconds before requesting another code.`,code:'OTP_RESEND_COOLDOWN',retryAfterSeconds:Math.ceil((60000-elapsed)/1000)});const resendWindowStart=user.emailVerificationResendWindowStartedAt?new Date(user.emailVerificationResendWindowStartedAt).getTime():0;const resendCount=Number(user.emailVerificationResends||0);if(resendWindowStart&&Date.now()-resendWindowStart<3600000&&resendCount>=5)return res.status(429).json({error:'Too many verification emails requested. Please try again later.',code:'OTP_RESEND_LIMIT'});const otp=createOtp();try{await sendVerificationEmail(user.email,user.name,otp);}catch(e){console.error(e);return res.status(503).json({error:'Unable to send a new verification email. Please try again.',code:'EMAIL_DELIVERY_FAILED'});}const withinWindow=resendWindowStart&&Date.now()-resendWindowStart<3600000;await users.updateOne({id:user.id},{$set:{emailVerificationOtpHash:hashToken(otp),emailVerificationExpiresAt:new Date(Date.now()+600000),emailVerificationAttempts:0,emailVerificationSentAt:new Date(),emailVerificationResendWindowStartedAt:withinWindow?new Date(resendWindowStart):new Date(),emailVerificationResends:withinWindow?resendCount+1:1}});res.json({message:'A new verification code has been sent.',cooldownSeconds:60});}catch(error){console.error(error);res.status(500).json({error:'Unable to resend verification code.',code:'OTP_RESEND_FAILED'});}});
app.post('/api/auth/login',async(req,res)=>{try{const database=await db(),users=database.collection('users'),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!emailPattern.test(email)||!password)return res.status(400).json({error:'Enter your email and password.',code:'INVALID_LOGIN'});const user=await users.findOne({email});if(!user||!user.passwordHash||!await bcrypt.compare(password,user.passwordHash))return res.status(401).json({error:'Email or password is incorrect.',code:'INVALID_CREDENTIALS'});if(user.emailVerified!==true)return res.status(403).json({error:'Please verify your email before signing in.',code:'EMAIL_NOT_VERIFIED'});res.json({user:{id:user.id,name:user.name,email:user.email},token:tokenFor(user)});}catch(error){console.error(error);res.status(500).json({error:'Unable to sign in.',code:'LOGIN_FAILED'});}});

app.get('/api/me',auth,async(req,res)=>{const database=await db();const user=await database.collection('users').findOne({id:req.user.sub},{projection:{passwordHash:0}});if(!user)return res.status(404).json({error:'User not found.'});const stores=await database.collection('stores').find({userId:user.id}).sort({createdAt:1}).toArray();res.json({user,store:stores[0]||null,stores});});
app.post('/api/store',auth,async(req,res)=>{const database=await db(),stores=database.collection('stores');const storeCount=await stores.countDocuments({userId:req.user.sub});if(storeCount>=2)return res.status(403).json({error:'Free accounts can have up to 2 stores.'});const name=String(req.body.storeName||'My Store'),slug=slugify(req.body.slug||name)||`store-${req.user.sub.slice(0,8)}`;if(await stores.findOne({slug}))return res.status(409).json({error:'That store URL is already in use.'});const store={id:randomUUID(),userId:req.user.sub,storeName:name,slug,tagline:String(req.body.tagline||'Shop with us'),vendorPhone:String(req.body.vendorPhone||''),deliveryFee:Number(req.body.deliveryFee||0),primaryColor:String(req.body.primaryColor||'#12392d'),logo:'',paymentDetails:'',deliveryZones:[],discounts:[],createdAt:now()};await stores.insertOne(store);res.status(201).json({store});});
app.put('/api/store',auth,async(req,res)=>{const database=await db(),stores=database.collection('stores'),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const allowed=['storeName','slug','tagline','vendorPhone','deliveryFee','primaryColor','logo','paymentDetails','deliveryZones','discounts'],patch={};for(const key of allowed)if(req.body[key]!==undefined)patch[key]=req.body[key];if(patch.slug!==undefined){patch.slug=slugify(patch.slug);if(await stores.findOne({slug:patch.slug,id:{$ne:store.id}}))return res.status(409).json({error:'That store URL is already in use.'});}if(patch.deliveryFee!==undefined)patch.deliveryFee=Number(patch.deliveryFee);await stores.updateOne({id:store.id,userId:req.user.sub},{$set:patch});res.json({store:await stores.findOne({id:store.id})});});
app.get('/api/products',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.json({products:[]});res.json({products:await database.collection('products').find({storeId:store.id}).sort({createdAt:-1}).toArray()});});
app.post('/api/products',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(400).json({error:'Create your store first.'});const product={id:randomUUID(),storeId:store.id,name:String(req.body.name||'Product'),price:Number(req.body.price||0),description:String(req.body.description||''),emoji:String(req.body.emoji||'🛍️'),stock:Number(req.body.stock??0),imageUrl:String(req.body.imageUrl||''),variants:Array.isArray(req.body.variants)?req.body.variants:[],active:req.body.active!==false,createdAt:now()};await database.collection('products').insertOne(product);res.status(201).json({product});});
app.put('/api/products/:id',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const products=database.collection('products'),current=await products.findOne({id:req.params.id,storeId:store.id});if(!current)return res.status(404).json({error:'Product not found.'});const allowed=['name','price','description','emoji','stock','imageUrl','variants','active'],patch={};for(const key of allowed)if(req.body[key]!==undefined)patch[key]=req.body[key];if(patch.price!==undefined)patch.price=Number(patch.price);if(patch.stock!==undefined)patch.stock=Number(patch.stock);if(patch.variants!==undefined)patch.variants=Array.isArray(patch.variants)?patch.variants:[];await products.updateOne({id:current.id,storeId:store.id},{$set:patch});res.json({product:await products.findOne({id:current.id})});});
app.delete('/api/products/:id',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const result=await database.collection('products').deleteOne({id:req.params.id,storeId:store.id});if(!result.deletedCount)return res.status(404).json({error:'Product not found.'});res.json({deleted:true});});
app.get('/api/storefront/:slug',async(req,res)=>{const database=await db(),store=await database.collection('stores').findOne({slug:req.params.slug});if(!store)return res.status(404).json({error:'Store not found.'});const products=await database.collection('products').find({storeId:store.id,active:true}).sort({createdAt:-1}).toArray();const publicStore={id:store.id,storeName:store.storeName,slug:store.slug,tagline:store.tagline,primaryColor:store.primaryColor,logo:store.logo,deliveryFee:store.deliveryFee,deliveryZones:Array.isArray(store.deliveryZones)?store.deliveryZones:[]};res.json({store:publicStore,products});});
async function createAlatPayVirtualAccount(order) {
  if (!alatPaySecretKey) throw new Error('ALATPAY_SECRET_KEY is not configured.');
  if (!alatPayBusinessId) throw new Error('ALATPAY_BUSINESS_ID is not configured.');
  const response = await fetch(`${alatPayBaseUrl}/api/v1/bankTransfer/virtualAccount`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Ocp-Apim-Subscription-Key': alatPaySecretKey },
    body: JSON.stringify({ businessId: alatPayBusinessId, businessName: 'AD3N1X', amount: Number(order.total), currency: 'NGN', orderId: order.id, description: `QuickCart order ${order.id}`, channel: 'WEB', customer: { email: String(order.customerEmail || ''), phone: String(order.customerPhone || ''), firstName: String(order.customerName || 'Customer').split(' ')[0], lastName: String(order.customerName || '').split(' ').slice(1).join(' ') || 'Customer', metadata: JSON.stringify({ quickCartOrderId: order.id, storeId: order.storeId }) } })
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok || data.status === false) throw new Error(data.message || 'ALATPay payment initialization failed.');
  return data.data || data;
}
app.post('/api/payments/alatpay/plan',auth,async(req,res)=>{try{const database=await db();const plan=String(req.body.plan||'Premium');const plans={Premium:4999,Business:9999};if(!plans[plan])return res.status(400).json({error:'Invalid plan.'});const user=await database.collection('users').findOne({id:req.user.sub});if(!user)return res.status(404).json({error:'User not found.'});const order={id:randomUUID(),storeId:'subscription',storeName:'AD3N1X',customerName:user.name||'QuickCart Seller',customerEmail:user.email,customerPhone:String(req.body.phone||''),subtotal:plans[plan],deliveryFee:0,discount:0,total:plans[plan],status:'new',paymentStatus:'pending',plan,userId:req.user.sub,createdAt:now()};await database.collection('orders').insertOne(order);const payment=await createAlatPayVirtualAccount(order);await database.collection('orders').updateOne({id:order.id},{$set:{paymentProvider:'alatpay',paymentStatus:'awaiting_transfer',paymentTransactionId:payment.transactionId||payment.id||'',paymentReference:payment.orderId||order.id,paymentAccountNumber:payment.virtualBankAccountNumber||'',paymentBankCode:payment.virtualBankCode||'',paymentExpiresAt:payment.expiredAt||null,paymentUpdatedAt:now()}});res.status(201).json({plan,orderId:order.id,transactionId:payment.transactionId||payment.id||null,accountNumber:payment.virtualBankAccountNumber||null,bankCode:payment.virtualBankCode||null,amount:payment.amount??order.total,currency:payment.currency||'NGN',expiresAt:payment.expiredAt||null,status:payment.status||'pending'});}catch(error){console.error(error);res.status(502).json({error:error.message||'Unable to initialize ALATPay plan payment.'});}});
app.post('/api/payments/alatpay',async(req,res)=>{try{const database=await db(),orderId=String(req.body.orderId||'').trim(),order=await database.collection('orders').findOne({id:orderId});if(!order)return res.status(404).json({error:'Order not found.'});const payment=await createAlatPayVirtualAccount(order);await database.collection('orders').updateOne({id:order.id},{$set:{paymentProvider:'alatpay',paymentStatus:'awaiting_transfer',paymentTransactionId:payment.transactionId||payment.id||'',paymentReference:payment.orderId||order.id,paymentAccountNumber:payment.virtualBankAccountNumber||'',paymentBankCode:payment.virtualBankCode||'',paymentExpiresAt:payment.expiredAt||null,paymentUpdatedAt:now()}});res.status(201).json({orderId:order.id,transactionId:payment.transactionId||payment.id||null,accountNumber:payment.virtualBankAccountNumber||null,bankCode:payment.virtualBankCode||null,amount:payment.amount??order.total,currency:payment.currency||'NGN',expiresAt:payment.expiredAt||null,status:payment.status||'pending'});}catch(error){console.error(error);res.status(502).json({error:error.message||'Unable to initialize ALATPay payment.'});}});
app.post('/api/payments/alatpay/callback',async(req,res)=>{try{const database=await db(),payload=req.body||{},data=payload.data||payload,orderId=String(data.orderId||data.virtualAccount?.orderId||'').trim(),transactionId=String(data.transactionId||data.id||data.virtualAccount?.transactionId||'').trim(),nipStatus=String(data.nipTransaction?.transactionStatus||'').toLowerCase(),status=String(data.status||data.transactionStatus||nipStatus||'').toLowerCase(),update={paymentProvider:'alatpay',paymentTransactionId:transactionId,paymentUpdatedAt:now()};if(['success','successful','completed','paid','true'].includes(status)){update.paymentStatus='paid';update.status='paid';}else if(['failed','failure','cancelled','canceled','expired'].includes(status))update.paymentStatus='failed';else if(status)update.paymentStatus=status;if(orderId)await database.collection('orders').updateOne({id:orderId},{$set:update});else if(transactionId)await database.collection('orders').updateOne({paymentTransactionId:transactionId},{$set:update});if(update.paymentStatus==='paid'){const paidOrder=orderId?await database.collection('orders').findOne({id:orderId}):transactionId?await database.collection('orders').findOne({paymentTransactionId:transactionId}):null;if(paidOrder?.storeId==='subscription'&&paidOrder.plan&&paidOrder.userId){const days=paidOrder.plan==='Business'?365:30;await database.collection('users').updateOne({id:paidOrder.userId},{$set:{plan:paidOrder.plan,planExpiresAt:new Date(Date.now()+days*86400000).toISOString(),planStartedAt:now(),planCancelledAt:null}});}}res.json({received:true});}catch(error){console.error(error);res.status(500).json({error:'Unable to process ALATPay callback.'});}});

// Monetization and promotion APIs
const PLAN_CONFIG={Free:{price:0,features:['Branded storefront','Products and orders','WhatsApp checkout','Basic analytics']},Premium:{price:4999,features:['Everything in Free','Advanced analytics','Discounts and promotions','Priority storefront tools']},Business:{price:9999,features:['Everything in Premium','Multiple storefronts','Business analytics','Priority support']}};
app.get('/api/plan',auth,async(req,res)=>{try{const database=await db(),user=await database.collection('users').findOne({id:req.user.sub});if(!user)return res.status(404).json({error:'User not found.'});const rawPlan=PLAN_CONFIG[user.plan]?user.plan:'Free',expiresAt=user.planExpiresAt||null,active=rawPlan==='Free'||!expiresAt||new Date(expiresAt)>new Date(),plan=active?rawPlan:'Free';res.json({plan,active,expiresAt,price:PLAN_CONFIG[plan].price,features:PLAN_CONFIG[plan].features});}catch(error){res.status(500).json({error:'Unable to load plan.'});}});
app.post('/api/plan/cancel',auth,async(req,res)=>{try{const database=await db(),result=await database.collection('users').updateOne({id:req.user.sub},{$set:{plan:'Free',planExpiresAt:null,planCancelledAt:now()}});if(!result.matchedCount)return res.status(404).json({error:'User not found.'});res.json({plan:'Free'});}catch(error){res.status(500).json({error:'Unable to cancel plan.'});}});
app.get('/api/discounts',auth,async(req,res)=>{try{const database=await db(),store=await getUserStore(database,req),user=await database.collection('users').findOne({id:req.user.sub});if(!store)return res.json({discounts:[]});if(!['Premium','Business'].includes(user?.plan))return res.status(403).json({error:'Discounts require Premium or Business.'});res.json({discounts:await database.collection('discounts').find({storeId:store.id}).sort({createdAt:-1}).toArray()});}catch(error){res.status(500).json({error:'Unable to load discounts.'});}});
app.post('/api/discounts',auth,async(req,res)=>{try{const database=await db(),store=await getUserStore(database,req),user=await database.collection('users').findOne({id:req.user.sub});if(!store)return res.status(404).json({error:'Store not found.'});if(!['Premium','Business'].includes(user?.plan))return res.status(403).json({error:'Discounts require Premium or Business.'});const code=String(req.body.code||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'');const type=String(req.body.type||'percent');const value=Number(req.body.value);if(!code||!['percent','fixed'].includes(type)||!Number.isFinite(value)||value<=0||(type==='percent'&&value>100))return res.status(400).json({error:'Invalid discount.'});if(await database.collection('discounts').findOne({storeId:store.id,code}))return res.status(409).json({error:'Discount code already exists.'});const discount={id:randomUUID(),storeId:store.id,code,type,value,expiresAt:req.body.expiresAt?new Date(req.body.expiresAt).toISOString():null,active:true,createdAt:now()};await database.collection('discounts').insertOne(discount);res.status(201).json({discount});}catch(error){res.status(500).json({error:error.message||'Unable to create discount.'});}});
app.delete('/api/discounts/:id',auth,async(req,res)=>{try{const database=await db(),store=await getUserStore(database,req),user=await database.collection('users').findOne({id:req.user.sub});if(!['Premium','Business'].includes(user?.plan))return res.status(403).json({error:'Discounts require Premium or Business.'});const result=await database.collection('discounts').deleteOne({id:req.params.id,storeId:store?.id});if(!result.deletedCount)return res.status(404).json({error:'Discount not found.'});res.json({deleted:true});}catch(error){res.status(500).json({error:'Unable to delete discount.'});}});
app.post('/api/discounts/validate',async(req,res)=>{try{const database=await db(),storeId=String(req.body.storeId||''),code=String(req.body.code||'').trim().toUpperCase(),discount=await database.collection('discounts').findOne({storeId,code,active:true});if(!discount)return res.status(404).json({valid:false,error:'Invalid discount code.'});if(discount.expiresAt&&new Date(discount.expiresAt)<=new Date())return res.status(400).json({valid:false,error:'Discount has expired.'});const subtotal=Math.max(0,Number(req.body.subtotal||0)),amount=discount.type==='percent'?subtotal*(discount.value/100):Math.min(subtotal,discount.value);res.json({valid:true,code:discount.code,type:discount.type,value:discount.value,amount:Math.round(amount*100)/100});}catch(error){res.status(500).json({error:'Unable to validate discount.'});}});

app.post('/api/orders',async(req,res)=>{const database=await db(),storeId=String(req.body.storeId||''),items=Array.isArray(req.body.items)?req.body.items:[],customerName=String(req.body.customerName||'').trim(),customerPhone=String(req.body.customerPhone||'').trim(),address=String(req.body.address||'').trim();if(!storeId||!customerName||!address||!items.length)return res.status(400).json({error:'Store, customer name, address and at least one item are required.'});if(!await database.collection('stores').findOne({id:storeId}))return res.status(404).json({error:'Store not found.'});const order={id:randomUUID(),storeId,customerName,customerPhone,address,items,subtotal:Number(req.body.subtotal||0),deliveryFee:Number(req.body.deliveryFee||0),discount:Number(req.body.discount||0),total:Number(req.body.total||0),status:'new',paymentStatus:'pending',createdAt:now()};await database.collection('orders').insertOne(order);if(customerPhone)await database.collection('customers').updateOne({storeId,phone:customerPhone},{$set:{storeId,name:customerName,phone:customerPhone,address,updatedAt:now()},$setOnInsert:{createdAt:now()}},{upsert:true});res.status(201).json({orderId:order.id});});
app.get('/api/orders',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.json({orders:[]});res.json({orders:await database.collection('orders').find({storeId:store.id}).sort({createdAt:-1}).toArray()});});
app.put('/api/orders/:id/status',auth,async(req,res)=>{const allowed=['new','confirmed','processing','ready','shipped','delivered','cancelled'];const status=String(req.body.status||'');if(!allowed.includes(status))return res.status(400).json({error:'Invalid order status.'});const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const result=await database.collection('orders').updateOne({id:req.params.id,storeId:store.id},{$set:{status,updatedAt:now()}});if(!result.matchedCount)return res.status(404).json({error:'Order not found.'});res.json({status});});

export default app;
