import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { MongoClient } from 'mongodb';
import { randomUUID, createHash } from 'node:crypto';

const app = express();
const frontendUrl = process.env.FRONTEND_URL || 'https://quick-cart-three-chi.vercel.app';
const allowedOrigins = new Set([frontendUrl, 'https://quick-cart-three-chi.vercel.app', 'http://localhost:5173', 'http://localhost:4173']);
const isAllowedOrigin = origin => !origin || allowedOrigins.has(origin) || /^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin);
const corsOptions = { origin: (origin, callback) => callback(null, isAllowedOrigin(origin)), methods: ['GET','HEAD','PUT','PATCH','POST','DELETE','OPTIONS'], allowedHeaders: ['Content-Type','Authorization','X-Store-Id'], optionsSuccessStatus: 204 };
app.use(cors(corsOptions));
app.options(/.*/, cors(corsOptions));
app.use(express.json({ limit: '2mb' }));

const mongoUri = process.env.MONGODB_URI;
const jwtSecret = process.env.JWT_SECRET;
const brevoApiKey = process.env.BREVO_API_KEY;
const brevoFromEmail = process.env.BREVO_FROM_EMAIL;
const brevoFromName = process.env.BREVO_FROM_NAME || 'QuickCart';
const alatPaySecretKey = process.env.ALATPAY_SECRET_KEY;
const alatPayPublicKey = process.env.ALATPAY_PUBLIC_KEY;
const alatPayBusinessId = process.env.ALATPAY_BUSINESS_ID;
const alatPayBaseUrl = process.env.ALATPAY_BASE_URL || 'https://apibox.alatpay.ng/bank-transfer';
if (!mongoUri) console.warn('MONGODB_URI is not configured.');
if (!jwtSecret) console.warn('JWT_SECRET is not configured.');
if (!brevoApiKey) console.warn('BREVO_API_KEY is not configured.');
if (!brevoFromEmail) console.warn('BREVO_FROM_EMAIL is not configured.');
if (!alatPaySecretKey) console.warn('ALATPAY_SECRET_KEY is not configured.');
if (!alatPayBusinessId) console.warn('ALATPAY_BUSINESS_ID is not configured.');

let dbPromise;
async function db() { if (!mongoUri) throw new Error('MONGODB_URI is not configured.'); if (!dbPromise) { const client = new MongoClient(mongoUri); dbPromise = client.connect().then(async c => { const database=c.db('quickcart'); await Promise.all([database.collection('users').createIndex({email:1},{unique:true}),database.collection('stores').createIndex({slug:1},{unique:true}),database.collection('stores').createIndex({userId:1,createdAt:1}),database.collection('products').createIndex({storeId:1,createdAt:-1}),database.collection('orders').createIndex({storeId:1,createdAt:-1}),database.collection('orders').createIndex({id:1},{unique:true}),database.collection('customers').createIndex({storeId:1,phone:1},{unique:true,partialFilterExpression:{phone:{$exists:true,$ne:''}}}),database.collection('discounts').createIndex({storeId:1,code:1},{unique:true})]); return database; }); } return dbPromise; }
function tokenFor(user) { if (!jwtSecret) throw new Error('JWT_SECRET is not configured.'); return jwt.sign({ sub: user.id, email: user.email, name: user.name }, jwtSecret, { expiresIn: '8h' }); }
async function auth(req, res, next) {
  try {
    const h=req.headers.authorization||'';
    const token=h.startsWith('Bearer ')?h.slice(7):'';
    if(!token||!jwtSecret)return res.status(401).json({error:'Authentication required.'});
    req.user=jwt.verify(token,jwtSecret);
    const database=await db();
    const user=await database.collection('users').findOne({id:req.user.sub},{projection:{lastActivityAt:1}});
    if(!user)return res.status(401).json({error:'Session expired. Please sign in again.'});
    const lastActivity = user.lastActivityAt ? new Date(user.lastActivityAt).getTime() : 0;
    if(lastActivity && Number.isFinite(lastActivity) && Date.now()-lastActivity > 30*60*1000) return res.status(401).json({error:'Your session expired after 30 minutes of inactivity. Please sign in again.'});
    await database.collection('users').updateOne({id:req.user.sub},{$set:{lastActivityAt:now()}});
    next();
  } catch(error) {
    if(error?.name==='TokenExpiredError') return res.status(401).json({error:'Your session has expired. Please sign in again.'});
    return res.status(401).json({error:'Invalid or expired session.'});
  }
}
const hashToken = token => createHash('sha256').update(token).digest('hex');
const now = () => new Date().toISOString();
const PLANS = {
  Free: { price: 0, maxStores: 2, maxProducts: 25, features: ['basic_catalog','whatsapp_checkout','orders'] },
  Premium: { price: 4999, maxStores: Infinity, maxProducts: Infinity, features: ['basic_catalog','whatsapp_checkout','orders','analytics','customers','inventory','discounts','branding','variants','delivery_zones','csv','advanced_orders'] },
  Business: { price: 9999, maxStores: Infinity, maxProducts: Infinity, features: ['basic_catalog','whatsapp_checkout','orders','analytics','customers','inventory','discounts','branding','variants','delivery_zones','csv','advanced_orders','advanced_reports','team_workflows','priority_support'] }
};
const planFor = user => PLANS[user?.subscriptionStatus === 'active' && PLANS[user.subscriptionPlan] ? user.subscriptionPlan : 'Free';
const requirePlan = feature => async (req,res,next) => {
  try {
    const database=await db();
    const user=await database.collection('users').findOne({id:req.user.sub},{projection:{subscriptionPlan:1,subscriptionStatus:1,subscriptionExpiresAt:1}});
    const active = user?.subscriptionStatus === 'active' && user?.subscriptionExpiresAt && new Date(user.subscriptionExpiresAt) > new Date();
    const plan = active ? (user.subscriptionPlan || 'Free') : 'Free';
    if (!PLANS[plan].features.includes(feature)) return res.status(402).json({error:'This feature requires a paid QuickCart plan.',code:'PLAN_REQUIRED',feature,plan});
    req.plan=plan;
    next();
  } catch(error) { res.status(500).json({error:'Unable to check plan access.'}); }
};
const slugify = value => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);
async function getUserStore(database, req) { const stores=database.collection('stores'); const requestedId=String(req.headers['x-store-id']||''); if(requestedId){ const selected=await stores.findOne({id:requestedId,userId:req.user.sub}); if(selected)return selected; } return stores.findOne({userId:req.user.sub},{sort:{createdAt:1}}); }

async function sendVerificationEmail(email,name,otp){
 if(!brevoApiKey) throw new Error('BREVO_API_KEY is not configured.');
 if(!brevoFromEmail) throw new Error('BREVO_FROM_EMAIL is not configured.');
 const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{accept:'application/json','api-key':brevoApiKey,'content-type':'application/json'},body:JSON.stringify({sender:{name:brevoFromName,email:brevoFromEmail},to:[{email,name}],subject:'Your QuickCart verification code',textContent:`Hi ${name||'there'}, your QuickCart verification code is ${otp}. It expires in 10 minutes.`,htmlContent:`<html><body style="font-family:Arial,sans-serif;background:#f5f8f6;padding:30px"><div style="max-width:520px;margin:auto;background:#fff;padding:32px;border-radius:16px"><h1>Welcome to QuickCart 👋</h1><p>Hi ${name||'there'},</p><p>Use this code to verify your email:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px;background:#eef5f1;padding:18px;text-align:center;border-radius:12px">${otp}</div><p>This code expires in 10 minutes.</p></div></body></html>`})});
 const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.message||'Unable to send verification email.'); return data;
}

app.get('/api/_healthcheck',async(_req,res)=>{try{const database=await db();await database.command({ping:1});res.json({ok:true,database:'quickcart',emailProvider:'brevo'});}catch(error){console.error(error);res.status(503).json({ok:false,error:error.message||'Database connection failed.'});}});
app.post('/api/auth/signup',async(req,res)=>{try{const database=await db(),users=database.collection('users');const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),name=String(req.body.name||'').trim();if(!email||password.length<6||!name)return res.status(400).json({error:'Name, email and a password of at least 6 characters are required.'});if(await users.findOne({email}))return res.status(409).json({error:'An account with that email already exists.'});const otp=String(Math.floor(100000+Math.random()*900000));const user={id:randomUUID(),name,email,passwordHash:await bcrypt.hash(password,12),emailVerified:false,emailVerificationOtpHash:hashToken(otp),emailVerificationExpiresAt:new Date(Date.now()+600000),emailVerificationAttempts:0,createdAt:now()};await users.insertOne(user);try{await sendVerificationEmail(email,name,otp);}catch(e){await users.deleteOne({id:user.id});throw e;}res.status(201).json({message:'Account created. Enter the verification code sent to your email.',requiresVerification:true,email});}catch(error){console.error(error);res.status(500).json({error:error.message||'Unable to create account.'});}});
app.post('/api/auth/verify-otp',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),otp=String(req.body.otp||'').trim();if(!email||!/^[0-9]{6}$/.test(otp))return res.status(400).json({error:'Enter the 6-digit verification code.'});const database=await db(),users=database.collection('users'),user=await users.findOne({email});if(!user)return res.status(404).json({error:'Account not found.'});if(user.emailVerified)return res.json({message:'Email is already verified.',token:tokenFor(user),user:{id:user.id,name:user.name,email:user.email}});if(user.emailVerificationAttempts>=5)return res.status(429).json({error:'Too many incorrect attempts. Request a new code.'});if(!user.emailVerificationExpiresAt||new Date(user.emailVerificationExpiresAt)<=new Date())return res.status(400).json({error:'This code has expired. Request a new code.'});if(hashToken(otp)!==user.emailVerificationOtpHash){await users.updateOne({id:user.id},{$inc:{emailVerificationAttempts:1}});return res.status(400).json({error:'Incorrect verification code.'});}await users.updateOne({id:user.id},{$set:{emailVerified:true},$unset:{emailVerificationOtpHash:'',emailVerificationExpiresAt:'',emailVerificationAttempts:''}});res.json({message:'Email verified successfully.',token:tokenFor({...user,emailVerified:true}),user:{id:user.id,name:user.name,email:user.email}});}catch(error){console.error(error);res.status(500).json({error:'Unable to verify email.'});}});
app.post('/api/auth/resend-otp',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Email is required.'});const database=await db(),users=database.collection('users'),user=await users.findOne({email});if(!user)return res.status(404).json({error:'No account was found with that email.'});if(user.emailVerified)return res.status(400).json({error:'That email is already verified. You can sign in.'});const otp=String(Math.floor(100000+Math.random()*900000));await users.updateOne({id:user.id},{$set:{emailVerificationOtpHash:hashToken(otp),emailVerificationExpiresAt:new Date(Date.now()+600000),emailVerificationAttempts:0}});await sendVerificationEmail(user.email,user.name,otp);res.json({message:'A new verification code has been sent.'});}catch(error){console.error(error);res.status(500).json({error:error.message||'Unable to resend verification code.'});}});
app.post('/api/auth/login',async(req,res)=>{try{const database=await db(),users=database.collection('users'),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),user=await users.findOne({email});if(!user||!await bcrypt.compare(password,user.passwordHash||''))return res.status(401).json({error:'Email or password is incorrect.'});if(!user.emailVerified)return res.status(403).json({error:'Please verify your email before signing in.',code:'EMAIL_NOT_VERIFIED'});await users.updateOne({id:user.id},{$set:{lastActivityAt:now()}});res.json({user:{id:user.id,name:user.name,email:user.email},token:tokenFor(user)});}catch(error){console.error(error);res.status(500).json({error:'Unable to sign in.'});}});
app.get('/api/me',auth,async(req,res)=>{const database=await db();const user=await database.collection('users').findOne({id:req.user.sub},{projection:{passwordHash:0}});if(!user)return res.status(404).json({error:'User not found.'});const stores=await database.collection('stores').find({userId:user.id}).sort({createdAt:1}).toArray();res.json({user,store:stores[0]||null,stores});});
app.post('/api/store',auth,async(req,res)=>{const database=await db(),stores=database.collection('stores'),user=await database.collection('users').findOne({id:req.user.sub},{projection:{subscriptionPlan:1,subscriptionStatus:1,subscriptionExpiresAt:1}});const plan=planFor(user);const storeCount=await stores.countDocuments({userId:req.user.sub});if(storeCount>=PLANS[plan].maxStores)return res.status(403).json({error:`${plan} plan store limit reached.`,code:'STORE_LIMIT'});const name=String(req.body.storeName||'My Store'),slug=slugify(req.body.slug||name)||`store-${req.user.sub.slice(0,8)}`;if(await stores.findOne({slug}))return res.status(409).json({error:'That store URL is already in use.'});const store={id:randomUUID(),userId:req.user.sub,storeName:name,slug,tagline:String(req.body.tagline||'Shop with us'),vendorPhone:String(req.body.vendorPhone||''),deliveryFee:Number(req.body.deliveryFee||0),primaryColor:String(req.body.primaryColor||'#12392d'),logo:'',paymentDetails:'',deliveryZones:[],discounts:[],createdAt:now()};await stores.insertOne(store);res.status(201).json({store});});
app.put('/api/store',auth,async(req,res)=>{const database=await db(),stores=database.collection('stores'),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const allowed=['storeName','slug','tagline','vendorPhone','deliveryFee','primaryColor','logo','paymentDetails','deliveryZones','discounts'],patch={};for(const key of allowed)if(req.body[key]!==undefined)patch[key]=req.body[key];if(patch.slug!==undefined){patch.slug=slugify(patch.slug);if(await stores.findOne({slug:patch.slug,id:{$ne:store.id}}))return res.status(409).json({error:'That store URL is already in use.'});}if(patch.deliveryFee!==undefined)patch.deliveryFee=Number(patch.deliveryFee);await stores.updateOne({id:store.id,userId:req.user.sub},{$set:patch});res.json({store:await stores.findOne({id:store.id})});});
app.get('/api/products',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.json({products:[]});res.json({products:await database.collection('products').find({storeId:store.id}).sort({createdAt:-1}).toArray()});});
app.post('/api/products',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(400).json({error:'Create your store first.'});const user=await database.collection('users').findOne({id:req.user.sub},{projection:{subscriptionPlan:1,subscriptionStatus:1,subscriptionExpiresAt:1}}),plan=planFor(user),count=await database.collection('products').countDocuments({storeId:store.id});if(count>=PLANS[plan].maxProducts)return res.status(403).json({error:`${plan} plan product limit reached.`,code:'PRODUCT_LIMIT'});const price=Number(req.body.price);const stock=Number(req.body.stock??0);if(!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0)return res.status(400).json({error:'Price and stock must be valid non-negative values.'});const product={id:randomUUID(),storeId:store.id,name:String(req.body.name||'Product'),price:Number(req.body.price||0),description:String(req.body.description||''),emoji:String(req.body.emoji||'🛍️'),stock:Number(req.body.stock??0),active:req.body.active!==false,createdAt:now()};await database.collection('products').insertOne(product);res.status(201).json({product});});
app.put('/api/products/:id',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.status(404).json({error:'Store not found.'});const patch={};for(const key of ['name','description','emoji','imageUrl','variants','active'])if(req.body[key]!==undefined)patch[key]=req.body[key];if(req.body.price!==undefined){const v=Number(req.body.price);if(!Number.isFinite(v)||v<0)return res.status(400).json({error:'Invalid price.'});patch.price=v;}if(req.body.stock!==undefined){const v=Number(req.body.stock);if(!Number.isInteger(v)||v<0)return res.status(400).json({error:'Stock must be a non-negative integer.'});patch.stock=v;}await database.collection('products').updateOne({id:req.params.id,storeId:store.id},{$set:{...patch,updatedAt:now()}});const product=await database.collection('products').findOne({id:req.params.id,storeId:store.id});if(!product)return res.status(404).json({error:'Product not found.'});res.json({product});});
app.delete('/api/products/:id',auth,async(req,res)=>{const database=await db(),store=await database.collection('stores').findOne({userId:req.user.sub});if(!store)return res.status(404).json({error:'Store not found.'});const result=await database.collection('products').deleteOne({id:req.params.id,storeId:store.id});if(!result.deletedCount)return res.status(404).json({error:'Product not found.'});res.json({deleted:true});});
app.get('/api/storefront/:slug',async(req,res)=>{const database=await db(),store=await database.collection('stores').findOne({slug:req.params.slug});if(!store)return res.status(404).json({error:'Store not found.'});const q=String(req.query.q||'').trim();const filter={storeId:store.id,active:true};if(q)filter.$or=[{name:{$regex:q,'$options':'i'}},{description:{$regex:q,'$options':'i'}}];const products=await database.collection('products').find(filter).sort({createdAt:-1}).toArray();res.json({store,products});});
app.get('/api/plan',auth,async(req,res)=>{const database=await db();const user=await database.collection('users').findOne({id:req.user.sub},{projection:{subscriptionPlan:1,subscriptionStatus:1,subscriptionExpiresAt:1}});const plan=planFor(user);res.json({plan,plans:PLANS,expiresAt:user?.subscriptionExpiresAt||null});});
app.get('/api/customers',auth,requirePlan('customers'),async(req,res)=>{const database=await db(),store=await getUserStore(database,req);if(!store)return res.json({customers:[]});res.json({customers:await database.collection('customers').find({storeId:store.id}).sort({updatedAt:-1}).toArray()});});
app.get('/api/discounts',auth,requirePlan('discounts'),async(req,res)=>{const database=await db(),store=await getUserStore(database,req);res.json({discounts:store?await database.collection('discounts').find({storeId:store.id}).sort({createdAt:-1}).toArray():[]});});
app.post('/api/discounts',auth,requirePlan('discounts'),async(req,res)=>{const database=await db(),store=await getUserStore(database,req);const code=String(req.body.code||'').trim().toUpperCase();const type=String(req.body.type||'percent');const value=Number(req.body.value);if(!store||!code||!['percent','fixed'].includes(type)||!Number.isFinite(value)||value<=0)return res.status(400).json({error:'Enter a valid discount.'});if(type==='percent'&&value>100)return res.status(400).json({error:'Percentage discount cannot exceed 100%.'});try{const discount={id:randomUUID(),storeId:store.id,code,type,value,expiresAt:req.body.expiresAt||null,active:req.body.active!==false,createdAt:now()};await database.collection('discounts').insertOne(discount);res.status(201).json({discount});}catch(error){if(error?.code===11000)return res.status(409).json({error:'That discount code already exists.'});throw error;}});
app.delete('/api/discounts/:id',auth,requirePlan('discounts'),async(req,res)=>{const database=await db(),store=await getUserStore(database,req);const result=await database.collection('discounts').deleteOne({id:req.params.id,storeId:store?.id});if(!result.deletedCount)return res.status(404).json({error:'Discount not found.'});res.json({deleted:true});});
app.put('/api/orders/:id/status',auth,async(req,res)=>{const database=await db(),store=await getUserStore(database,req);const allowed=['new','confirmed','processing','ready','shipped','delivered','cancelled'];const status=String(req.body.status||'');if(!allowed.includes(status))return res.status(400).json({error:'Invalid order status.'});const result=await database.collection('orders').updateOne({id:req.params.id,storeId:store?.id},{$set:{status,updatedAt:now()}});if(!result.matchedCount)return res.status(404).json({error:'Order not found.'});res.json({updated:true,status});});

async function createAlatPayVirtualAccount(order) {
  if (!alatPaySecretKey) throw new Error('ALATPAY_SECRET_KEY is not configured.');
  if (!alatPayBusinessId) throw new Error('ALATPAY_BUSINESS_ID is not configured.');
  const response = await fetch(`${alatPayBaseUrl}/api/v1/bankTransfer/virtualAccount`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Ocp-Apim-Subscription-Key': alatPaySecretKey },
    body: JSON.stringify({businessId: alatPayBusinessId,businessName: 'AD3N1X',amount: Number(order.total),currency: 'NGN',orderId: order.id,description: `QuickCart order ${order.id}`,channel: 'WEB',customer: {email: String(order.customerEmail || ''),phone: String(order.customerPhone || ''),firstName: String(order.customerName || 'Customer').split(' ')[0],lastName: String(order.customerName || '').split(' ').slice(1).join(' ') || 'Customer',metadata: JSON.stringify({ quickCartOrderId: order.id, storeId: order.storeId })}})
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok || data.status === false) throw new Error(data.message || 'ALATPay payment initialization failed.');
  return data.data || data;
}
app.post('/api/payments/alatpay/plan',auth,async(req,res)=>{try{const database=await db();const plan=String(req.body.plan||'Premium');const plans={Premium:4999,Business:9999};if(!plans[plan])return res.status(400).json({error:'Invalid plan.'});const user=await database.collection('users').findOne({id:req.user.sub});if(!user)return res.status(404).json({error:'User not found.'});const order={id:randomUUID(),storeId:'subscription',storeName:'AD3N1X',customerUserId:user.id,customerName:user.name||'QuickCart Seller',customerEmail:user.email,customerPhone:String(req.body.phone||''),subtotal:plans[plan],deliveryFee:0,discount:0,total:plans[plan],status:'new',paymentStatus:'pending',plan,createdAt:now()};await database.collection('orders').insertOne(order);const payment=await createAlatPayVirtualAccount(order);await database.collection('orders').updateOne({id:order.id},{$set:{paymentProvider:'alatpay',paymentStatus:'awaiting_transfer',paymentTransactionId:payment.transactionId||payment.id||'',paymentReference:payment.orderId||order.id,paymentAccountNumber:payment.virtualBankAccountNumber||'',paymentBankCode:payment.virtualBankCode||'',paymentExpiresAt:payment.expiredAt||null,paymentUpdatedAt:now()}});res.status(201).json({plan,orderId:order.id,transactionId:payment.transactionId||payment.id||null,accountNumber:payment.virtualBankAccountNumber||null,bankCode:payment.virtualBankCode||null,amount:payment.amount??order.total,currency:payment.currency||'NGN',expiresAt:payment.expiredAt||null,status:payment.status||'pending'});}catch(error){console.error(error);res.status(502).json({error:error.message||'Unable to initialize ALATPay plan payment.'});}});
app.post('/api/payments/alatpay',async(req,res)=>{try{const database=await db();const orderId=String(req.body.orderId||'').trim();const order=await database.collection('orders').findOne({id:orderId});if(!order)return res.status(404).json({error:'Order not found.'});const payment=await createAlatPayVirtualAccount(order);await database.collection('orders').updateOne({id:order.id},{$set:{paymentProvider:'alatpay',paymentStatus:'awaiting_transfer',paymentTransactionId:payment.transactionId||payment.id||'',paymentReference:payment.orderId||order.id,paymentAccountNumber:payment.virtualBankAccountNumber||'',paymentBankCode:payment.virtualBankCode||'',paymentExpiresAt:payment.expiredAt||null,paymentUpdatedAt:now()}});res.status(201).json({orderId:order.id,transactionId:payment.transactionId||payment.id||null,accountNumber:payment.virtualBankAccountNumber||null,bankCode:payment.virtualBankCode||null,amount:payment.amount??order.total,currency:payment.currency||'NGN',expiresAt:payment.expiredAt||null,status:payment.status||'pending'});}catch(error){console.error(error);res.status(502).json({error:error.message||'Unable to initialize ALATPay payment.'});}});
app.get('/api/payments/alatpay/status',auth,async(req,res)=>{try{const database=await db();const orderId=String(req.query.orderId||'').trim();if(!orderId)return res.status(400).json({error:'Order ID is required.'});const order=await database.collection('orders').findOne({id:orderId,storeId:'subscription',customerEmail:req.user.email});if(!order)return res.status(404).json({error:'Payment not found.'});res.json({orderId:order.id,plan:order.plan||null,paymentStatus:order.paymentStatus||'pending',status:order.status||'new',amount:order.total,expiresAt:order.paymentExpiresAt||null});}catch(error){console.error(error);res.status(500).json({error:'Unable to check payment status.'});}});
app.post('/api/payments/alatpay/callback',async(req,res)=>{try{const database=await db();const payload=req.body||{};const data=payload.data||payload;const orderId=String(data.orderId||data.virtualAccount?.orderId||'').trim();const transactionId=String(data.transactionId||data.id||data.virtualAccount?.transactionId||'').trim();const nipStatus=String(data.nipTransaction?.transactionStatus||'').toLowerCase();const status=String(data.status||data.transactionStatus||nipStatus||'').toLowerCase();const amount=Number(data.amount??data.virtualAccount?.amount??data.nipTransaction?.amount??0);const currency=String(data.currency||data.virtualAccount?.currency||'').toUpperCase();const success=['success','successful','completed','paid','true'].includes(status);const failed=['failed','failure','cancelled','canceled','expired'].includes(status);let order=null;if(orderId)order=await database.collection('orders').findOne({id:orderId});if(!order&&transactionId)order=await database.collection('orders').findOne({paymentTransactionId:transactionId});if(!order)return res.status(404).json({received:false,error:'Order not found.'});const amountMatches=!amount||Math.round(amount*100)===Math.round(Number(order.total)*100);const currencyMatches=!currency||currency==='NGN';const update={paymentProvider:'alatpay',paymentTransactionId:transactionId||order.paymentTransactionId||'',paymentUpdatedAt:now(),paymentCallback:payload};if(success&&amountMatches&&currencyMatches){update.paymentStatus='paid';update.status='paid';if(order.plan){const expires=new Date();expires.setMonth(expires.getMonth()+1);await database.collection('users').updateOne({id:order.customerUserId||order.userId||''},{$set:{subscriptionPlan:order.plan,subscriptionStatus:'active',subscriptionExpiresAt:expires.toISOString(),subscriptionUpdatedAt:now()}});}}else if(failed){update.paymentStatus='failed';}else if(success&&(!amountMatches||!currencyMatches)){update.paymentStatus='failed';update.paymentFailureReason='Payment amount or currency did not match the QuickCart order.';}else if(status){update.paymentStatus=status;}await database.collection('orders').updateOne({id:order.id},{$set:update});res.json({received:true,processed:true,paymentStatus:update.paymentStatus||order.paymentStatus});}catch(error){console.error(error);res.status(500).json({error:'Unable to process ALATPay callback.'});}});
app.post('/api/orders',async(req,res)=>{const database=await db(),storeId=String(req.body.storeId||''),items=Array.isArray(req.body.items)?req.body.items:[],customerName=String(req.body.customerName||'').trim(),customerPhone=String(req.body.customerPhone||'').trim(),address=String(req.body.address||'').trim();if(!storeId||!customerName||!address||!items.length)return res.status(400).json({error:'Store, customer name, address and at least one item are required.'});if(!await database.collection('stores').findOne({id:storeId}))return res.status(404).json({error:'Store not found.'});const order={id:randomUUID(),storeId,customerName,customerPhone,address,items,subtotal:Number(req.body.subtotal||0),deliveryFee:Number(req.body.deliveryFee||0),discount:Number(req.body.discount||0),total:Number(req.body.total||0),status:'new',paymentStatus:'pending',createdAt:now()};await database.collection('orders').insertOne(order);if(customerPhone)await database.collection('customers').updateOne({storeId,phone:customerPhone},{$set:{storeId,name:customerName,phone:customerPhone,address,updatedAt:now()},$setOnInsert:{createdAt:now()}},{upsert:true});res.status(201).json({orderId:order.id});});
app.get('/api/orders',auth,async(req,res)=>{const database=await db(),store=await database.collection('stores').findOne({userId:req.user.sub});if(!store)return res.json({orders:[]});res.json({orders:await database.collection('orders').find({storeId:store.id}).sort({createdAt:-1}).toArray()});});

export default app;
